# Generated by Django 6.0 on 2026-01-19 22:52

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_type',
            field=models.CharField(choices=[('text', 'Text'), ('img', 'Image'), ('video', 'Video'), ('docs', 'Document'), ('audio', 'Audio')], default='text', max_length=15),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
