# Generated by Django 6.0 on 2026-01-26 09:13

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_chatgroup_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='category',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('docs', 'Document'), ('audio', 'Audio')], default='chat', max_length=15),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
