# Generated by Django 6.0 on 2025-12-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_otp_code_user_otp_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created',
        ),
    ]
