# Generated by Django 6.0 on 2025-12-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_otp_code_remove_user_otp_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spokenlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoken_language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hourlyrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prof_photo',
            field=models.ImageField(blank=True, default='profile_images/default-black.png', null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='spoken_languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoken', to='user.spokenlang'),
        ),
    ]
