# Generated by Django 6.0 on 2025-12-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_spokenlang_user_bio_user_hourlyrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='spoken_languages',
        ),
    ]
