# Generated by Django 6.0 on 2025-12-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_spoken_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spoken_languages',
            field=models.ManyToManyField(blank=True, to='user.spokenlang'),
        ),
        migrations.AlterField(
            model_name='spokenlang',
            name='spoken_language',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
