# Generated by Django 6.0 on 2025-12-16 07:00

import user.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.CustomUserManager()),
            ],
        ),
    ]
