# Generated by Django 6.0 on 2026-01-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_follow_is_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreport',
            name='Reason',
        ),
    ]
