# Generated by Django 6.0 on 2026-01-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_postreport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='reason',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
    ]
