# Generated by Django 6.0 on 2026-01-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_mentorrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prof_photo',
        ),
    ]
