# Generated by Django 6.0 on 2026-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_user_prof_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
