# Generated by Django 6.0 on 2026-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_prof_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_photo',
            field=models.URLField(blank=True, default='https://sayit1.s3.ap-south-1.amazonaws.com/profile_images/default-black.png', null=True),
        ),
    ]
