# Generated by Django 6.0 on 2026-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postreport',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
