# Generated by Django 6.0 on 2026-02-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_booking_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_mentor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
